# 使用docker build ./ 进行构建
# https://hub.docker.com/_/php/
FROM registry.cn-beijing.aliyuncs.com/mengyunzhi/thinkphp:development
# 复制php.ini至conf.d文件夹。覆盖默认配置
COPY config/php.ini /usr/local/etc/php/conf.d/paper.ini